[project]
name = "3DMarkScoreScraper"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "openpyxl>=3.1.2",
    "pandas>=2.2.2",
    "questionary>=2.0.1",
    "requests>=2.32.3",
    "tenacity>=8.4.1",
    "tqdm>=4.66.4",
]